name: Build and Test

on: [push, pull_request]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Setup Android Environment
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: |
            build-tools;28.0.3
            platforms;android-28

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test --info
